version: '3'

services:
  server:
    image: algoritm211/nestjs-rest-api
    command: npm run start:dev
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      - DB_HOST=${DB_HOST}
      - DB_PORT=${DB_PORT}
      - DB_USERNAME=${DB_USERNAME}
      - DB_PASSWORD=${DB_PASSWORD}
    volumes:
      - .:/app
      - ./app/node_modules
    ports:
      - "5000:5000"
    container_name: nestjs-rest-api
    depends_on:
      - postgres
    links:
      - postgres:postgres-db

  postgres:
    image: postgres
    restart: always
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    container_name: postgres-db
    ports:
      - "5432:5432"
    volumes:
      - ./pgdata:/var/lib/postgresql/data
